name: CI
# To test fastlane build commands on your local machine, install fastlane.
# sudo gem install fastlane -NV
#

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Push events on master + devel branch    
      - devel # Push events on master + devel branch            
    tags:
      - '*' # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
env:
  RELEASE: release
  
jobs:
 
  # Run unit tests
  unit-tests:
    name: Build and run unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest] # , macos-latest
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Checkout submodules
      run: |
        echo Checkout submodules
        #git fetch origin
        git submodule sync
        git submodule update --init --recursive 

    - name: Build unit tests.
      run: |
        rm -rf build
        mkdir build
        pushd build
        cmake ..
        make -j4
        popd

    - name: Run unit tests.
      if: (github.workflow != 'CD')
      run: |
        pushd build
        ctest -j4 --verbose
        popd        
  
