name: CI
# To test fastlane build commands on your local machine, install fastlane.
# sudo gem install fastlane -NV
#

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - devel
      - feat/chfo/210409_ga
    tags:
      - '*' # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
env:
  RELEASE: release
  
jobs:
 
  # Run unit tests
  unit-tests:
    name: Build and run unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest] # , macos-latest
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule sync
        git submodule update --init --recursive 

    - name: Run cmake
      if: (matrix.platform == 'ubuntu-latest') || (matrix.platform == 'macos-latest') || (matrix.platform == 'windows-latest')
      run: |
        mkdir build
        pushd build
        cmake ..
        popd

    - name: Build unit tests (ubuntu or macos).
      if: (matrix.platform == 'ubuntu-latest') || (matrix.platform == 'macos-latest')
      run: |
        pushd build
        make -j4
        popd

    - name: Build unit tests (windows).
      if: (matrix.platform == 'windows-latest')
      run: |
        pushd build
        msbuild roughtime_cpp_test.sln        
        popd

    - name: Run unit tests.
      if: (github.workflow != 'CD')
      run: |
        pushd build
        ctest -j4 --verbose
        popd        
  
